ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ProyectoWebApp.urls')),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('pedidos/', include('pedidos.urls')),

]

blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.blog, name="blog"),
    path('categoria/<int:categoria_id>/', views.categoria, name="categoria"),
]

contacto/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.contacto, name="contacto"),

]

contacto/models.py
from django.db import models

# Create your models here.

contacto/forms.py
from django import forms


class FormularioContacto(forms.Form):
    nombre = forms.CharField(label="Nombre", required=True)
    email = forms.CharField(label="Email", max_length=100)
    contenido = forms.CharField(label="Contenido",widget=forms.Textarea)

contacto/views.py
from django.shortcuts import render, redirect
from .forms import FormularioContacto
from django.core.mail import EmailMessage



# Create your views here.
def contacto(request):
    formulario_contacto=FormularioContacto()

    if request.method=="POST":
        formulario_contacto=FormularioContacto(data=request.POST)
        if formulario_contacto.is_valid():
            nombre=request.POST.get("nombre")
            email=request.POST.get("email")
            contenido=request.POST.get("contenido")

            email=EmailMessage("Mensaje desde app django", 
                               "El usuario con nombre {} con la direccion de correo {} escribe los siguiente: \n\n {}".format(nombre,email,contenido),
                               "", ["nicolasmunozj0@gmail.com"],reply_to=[email])
            
            try:    
                email.send()
                return redirect("/contacto/?valido")
            except:
                return redirect("/contacto/?novalido")
        
    return render(request, "contacto/contacto.html", {'miFormulario':formulario_contacto})

contacto/templates/contacto/contacto.html
{% extends "ProyectoWebApp/base.html" %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row justify-content-center" style="margin-bottom: 20px;">
    <div class="col-md-6">
      <div class="card mt-5">
        <div class="card-header custom-card-header">
            <h2 class="text-center">Formulario de Contacto</h2>
        </div>        
        <div class="card-body" >
            {% if "valido" in request.GET %}
              <p style="color: black;">Informacion enviada</p>
            {% endif %}
          <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_nombre" class="font-weight-bold">Nombre:</label>
              <input type="text" class="form-control" id="id_nombre" name="nombre" placeholder="Ingrese su nombre" required>
            </div>
            <div class="form-group">
              <label for="id_email" class="font-weight-bold">Email:</label>
              <input type="email" class="form-control" id="id_email" name="email" placeholder="Ingrese su correo electrónico" required>
            </div>
            <div class="form-group">
              <label for="id_contenido" class="font-weight-bold">Contenido:</label>
              <textarea class="form-control" id="id_contenido" name="contenido" rows="5" placeholder="Ingrese su mensaje"></textarea>
            </div>
            <div class="text-center">
            <button type="submit" class="btn btn-enviar ">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}