ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ProyectoWebApp.urls')),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('pedidos/', include('pedidos.urls')),

]

blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.blog, name="blog"),
    path('categoria/<int:categoria_id>/', views.categoria, name="categoria"),
]

carro/urls.py
from django.urls import path
from . import views

app_name="carro"


urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregarProducto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminarProducto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restarProducto, name="restar"),
    path("limpiar/", views.limpiarCarro, name="limpiar"),

]

carro/models.py
from django.db import models

# Create your models here.

carro/views.py
from django.shortcuts import render
from .carro import Carro
from tienda.models import Producto
from django.shortcuts import redirect
# Create your views here.

def agregarProducto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect("tienda")


def eliminarProducto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect("tienda")

def restarProducto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect("tienda")

def limpiarCarro(request):
    carro=Carro(request)
    carro.limpiar_carro()
    return redirect("tienda")

carro/templates/carro/widget.html
<table class="table-bordered" style="color: rgb(0, 0, 0);">

    <thead>

        <tr>
            <th colspan="3" class="text-center">
                carro compras
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>
        </tr>

    </thead>
    <tbody>

        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}

            <tr class="text-center">

                <td>{{value.nombre}}</td>
                <td>{{value.cantidad}}</td>
                <td>

                    <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                    <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a> <br>

                    {{value.precio}} $

                </td>

            </tr>

            {% endfor %}

        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">

                        sin productos

                    </div>
                </td>
            </tr>
        {% endif %}

    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">

                <p>total:{{importe_total_carro}} $</p>

            </td>
        </tr>

        {% if request.session.carro.items %}
        
            <tr>

                <td colspan="3" style="text-align: center;">

                   <a href="{% url 'pasarela_pago' %}" class="btn btn-success">Comprarr</a>
    
                </td>
                
            </tr>

        {% endif %}

    </tfoot>



</table>